version: "3"
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
